var i = 0;
var t = 0;
var nlclass = "hunter";
var nlclassPatch = "hunter";

nltree[i] = "Beast Mastery"; i++;
nltree[i] = "Marksmanship"; i++;
nltree[i] = "Survival"; i++;

i = 0;

nltalent[i] = ["Improved Aspect of the Hawk"]; i++;
nltalent[i] = ["Endurance Training"]; i++;
nltalent[i] = ["Focused Fire"]; i++;
nltalent[i] = ["Improved Aspect of the Monkey"]; i++; 
nltalent[i] = ["Thick Hide"]; i++;
nltalent[i] = ["Improved Revive Pet"]; i++;
nltalent[i] = ["Pathfinding"]; i++;
nltalent[i] = ["Bestial Swiftness"]; i++;
nltalent[i] = ["Unleashed Fury"]; i++;
nltalent[i] = ["Improved Mend Pet"]; i++;
nltalent[i] = ["Ferocity"]; i++;
nltalent[i] = ["Spirit Bond"]; i++;
nltalent[i] = ["Intimidation"]; i++;
nltalent[i] = ["Bestial Discipline"]; i++;
nltalent[i] = ["Animal Handler"]; i++;
nltalent[i] = ["Frenzy"]; i++;
nltalent[i] = ["Ferocious Inspiration"]; i++;
nltalent[i] = ["Bestial Wrath"]; i++;
nltalent[i] = ["Catlike Reflexes"]; i++;
nltalent[i] = ["Serpent's Swiftness"]; i++;
nltalent[i] = ["The Beast Within"]; i++;

//marksmanship talents
nltalent[i] = ["Improved Concussive Shot"]; i++;
nltalent[i] = ["Lethal Shots"]; i++;
nltalent[i] = ["Improved Hunter's Mark"]; i++;
nltalent[i] = ["Efficiency"]; i++;
nltalent[i] = ["Go for the Throat"]; i++;
nltalent[i] = ["Improved Arcane Shot"]; i++;
nltalent[i] = ["Aimed Shot"]; i++;
nltalent[i] = ["Rapid Killing"]; i++;
nltalent[i] = ["Improved Stings"]; i++;
nltalent[i] = ["Mortal Shots"]; i++;
nltalent[i] = ["Concussive Barrage"]; i++;
nltalent[i] = ["Scatter Shot"]; i++;
nltalent[i] = ["Barrage"]; i++;
nltalent[i] = ["Combat Experience"]; i++;
nltalent[i] = ["Ranged Weapon Specialization"]; i++;
nltalent[i] = ["Careful Aim"]; i++;
nltalent[i] = ["Trueshot Aura"]; i++;
nltalent[i] = ["Improved Barrage"]; i++;
nltalent[i] = ["Master Marksman"]; i++;
nltalent[i] = ["Silencing Shot"]; i++;

//shadow talents
nltalent[i] = ["Monster Slaying"]; i++;
nltalent[i] = ["Humanoid Slaying"]; i++;
nltalent[i] = ["Hawk Eye"]; i++;
nltalent[i] = ["Savage Strikes"]; i++;
nltalent[i] = ["Entrapment"]; i++;
nltalent[i] = ["Deflection"]; i++;
nltalent[i] = ["Improved Wing Clip"]; i++;
nltalent[i] = ["Clever Traps"]; i++;
nltalent[i] = ["Survivalist"]; i++;
nltalent[i] = ["Deterrence"]; i++;
nltalent[i] = ["Trap Mastery"]; i++;
nltalent[i] = ["Surefooted"]; i++;
nltalent[i] = ["Improved Feign Death"]; i++;
nltalent[i] = ["Survival Instincts"]; i++;
nltalent[i] = ["Killer Instinct"]; i++;
nltalent[i] = ["Counterattack"]; i++;
nltalent[i] = ["Resourcefulness"]; i++;
nltalent[i] = ["Lightning Reflexes"]; i++;
nltalent[i] = ["Thrill of the Hunt"]; i++;
nltalent[i] = ["Wyvern Sting"]; i++;
nltalent[i] = ["Expose Weakness"]; i++;
nltalent[i] = ["Master Tactician"]; i++;
nltalent[i] = ["Readiness"]; i++;
jsLoaded=true;//needed for ajax script loading
